apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "review-service"
  namespace: "default"
  labels:
    app: "review-service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "review-service"
  template:
    metadata:
      labels:
        app: "review-service"
    spec:
      containers:
      - name: "review-service-sha256-1"
        image: "eu.gcr.io/junction-hack22esp-7057/review-service@sha256:ac2b6bc7ae84933acc37b807bec4f7000b8da446b62de6c5145fb8a13c2d43e2"
