apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "review-service"
  namespace: "default"
  labels:
    app: "review-service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "review-service"
  template:
    metadata:
      labels:
        app: "review-service"
    spec:
      containers:
      - name: "reviews-service-sha256-1"
        image: "eu.gcr.io/junction-hack22esp-7057/reviews-service@sha256:724496ca266f951623b23d1f4734ca59a04379454ce4d551a9986f258dff975d"
