
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "google-reviews"
  namespace: "default"
  labels:
    app: "google-reviews"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "google-reviews"
  template:
    metadata:
      labels:
        app: "google-reviews"
    spec:
      containers:
      - name: "google-reviews-sha256-1"
        image: "eu.gcr.io/junction-hack22esp-7057/google-reviews@sha256:40cfc64d11826a5e1411760acfa2630d5fd6f2cfe4b31adfa81d6db589662155"
