
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "google-reviews"
  namespace: "default"
  labels:
    app: "google-reviews"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "google-reviews"
  template:
    metadata:
      labels:
        app: "google-reviews"
    spec:
      containers:
      # TODO
