apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "front"
  namespace: "default"
  labels:
    app: "front"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "front"
  template:
    metadata:
      labels:
        app: "front"
    spec:
      containers:
      - name: "front-sha256-1"
        image: "eu.gcr.io/junction-hack22esp-7057/front@sha256:8c12358e34ba004ae82adbac204e6952851969cee577a2edee87ead237791e0a"
